### ISSUE TITLE
dripip github action

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/dripip#57]
https://help.github.com/en/actions/building-actions/creating-a-javascript-action

Instead of this:

```yml
      - name: Make release
        id: release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          yarn -s dripip preview --json > result.json
          result=$(cat result.json)
          echo '==> Publish Result'
          jq '.' <<< $result
      - name: Save publish result
        uses: actions/upload-artifact@v1
        with:
          name: published
          path: result.json
```
This
```yml
- uses: prisma-labs/dripip
  with:
    npm_token: ${{ secrets.NPM_TOKEN }}    
```

For handling the artifacts part, refer to this issue which mentions more https://github.com/actions/upload-artifact/issues/62.
