### ISSUE TITLE
unexpected appended `:` on package publish

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/dripip#98]
Strange problem with `graphql-request` publishing on CI wherein there is an unexpected appended `:` character.

```yaml
      - name: Make release
        id: release
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          yarn -s dripip preview --json > result.json
          echo '==> Publish Result'
          jq '.' < result.json
```

https://github.com/prisma-labs/graphql-request/runs/1406452900#step:7:29
